### ISSUE TITLE
Having trouble getting the results from informationFlowMatting()

### ISSUE THREAD

**Issue by ChunHsinWang** [yaksoy/AffinityBasedMattingToolbox#1] opened 2017-03-24 09:24 UTC
Hi yaksoy,

Thank you for providing the matlab code for your interesting paper on information flow matting. However, I am not able to get the results from informationFlowMatting() function, the returned a_ifm contains nothing but zeros. The closedFormMatting() however seems to run fine without any problem. I've tried to trace the problems and found out that calculated Lap sparse matrix contains all zeros before pcg, but not sure how to solve it. I've ran the program with sample images provided in the code, with matlab 2015. Thank you for the help :)

**Comment by mikirui** [comment] 2017-04-21 04:39
@ChunHsinWang I met the problem too, and then I change the default parameter setting and let `params.mattePostTrim = true` and it seems informationFlowMatting() with param can work but it do not get a good result, I don't know whether there are any better setting to get better results.

**Comment by yaksoy** [comment] 2017-04-21 18:17
Hi,

@ChunHsinWang sorry I'm late to reply. I couldn't reproduce the issue and setting params.mattePostTrim = true will just give you a binary trimap (alphas are either 0 or 1) if the result itself is all zeros as in your case. 

Could you check if when the Laplacian becomes all-zero (or maybe has some NaN's or Inf's?) in the informationFlowMatting function? The lines in question are after 59, after 61 and after 63.

**Comment by ChunHsinWang** [comment] 2017-04-22 13:29
@yaksoy 

sorry when I said the Laplacian matrix is all-zero seems to be incorrect, due to the display setting in Matlab. After setting the display format to long,  however, the Laplacian I get from line 58 is very small, as following:

              (85266,79081)                 0.000141582394237
              (70070,79082)                -0.000008291496018
              (71755,79082)                 0.000052345601334
              (72887,79082)                -0.000131941436773

after line 59 the Lap becomes even smaller, something like this:

              (71772,76282)                -0.000001038613679
              (71773,76282)                -0.000001152876608
              (71774,76282)                 0.000001018859625
              (71775,76282)                 0.000001219765739
              (71776,76282)                -0.000000587787521

I've compared with the Laplacian in closed form matting which look something like this:

              (79022,79583)                -0.039145617973469
              (79581,79583)                 0.005849347021137
              (79582,79583)                -0.090237347602354
              (79583,79583)                 0.643901243683309
              (79584,79583)                -0.185344326950098
              (79585,79583)                -0.024437851840488

which is much more reasonable.

Thank you for your help.

**Comment by ChunHsinWang** [comment] 2017-04-22 17:31
An update on this issue,

I've tried the 2016b version of Matlab on a different computer, the informationFlowMatting() seems to be running correctly.

**Comment by mikirui** [comment] 2017-04-22 18:10
I also run the code with matlab 2015 when I met the problem, so maybe I should also try another matlab version.

**Comment by yaksoy** [comment] 2017-04-22 19:58
It was caused by the matrix inversion in localLinearEmbedding, which is apparently less numerically stable in Matlab 2015. It should be fixed now.

**Closed as completed by yaksoy** 2017-04-22 19:58 UTC
